apiVersion: v1
kind: Service
metadata:
  name: site-superati
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1010
      targetPort: 1010
      name: site-superati
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: site-superati
  labels:
    app: site-superati
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: site-superati
        tier: site-superati
    spec:
      containers:
      - image: quirinobytes/site-superati
        name: site-superati
        securityContext:
          privileged: true
        ports:
        - containerPort: 1010
          name: site-superati
        volumeMounts:
        # - name: jenkins-persistent-storage
        #   mountPath: /var/jenkins_home
        - name: docker
          mountPath: /var/run/docker.sock 
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      # - name: jenkins-persistent-storage
        # persistentVolumeClaim:
        #   claimName: jenkins-claim
