apiVersion: extensions/v1beta1
kind: Ingress
spec:
  rules:
  - host: www.superati.com.br
    http:
      paths:
      - backend:
          serviceName: ingress-13757f9e91a0f5ec888fdc7ed0def098
          servicePort: 1010
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: site-superati
  labels:
    app: site-superati
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: site-superati
        tier: site-superati
    spec:
      containers:
      - image: quirinobytes/site-superati
        name: site-superati
        securityContext:
          privileged: true
        ports:
        - containerPort: 1010
          name: site-superati
        volumeMounts:
        # - name: jenkins-persistent-storage
        #   mountPath: /var/jenkins_home
        - name: docker
          mountPath: /var/run/docker.sock 
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      # - name: jenkins-persistent-storage
        # persistentVolumeClaim:
        #   claimName: jenkins-claim
